[package]
name = "tn-auth-service"
version.workspace = true
edition.workspace = true

[dependencies]
tn-common = { path = "../common" }
tn-domain = { path = "../domain" }
tn-infra  = { path = "../infra" }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

